config/routes.rb
Rails.application.routes.draw do

  get 'order/information'

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "edit", to: "devise/registrations#edit"
  end

  root 'static_pages#home'
  match '/admin', to: 'admin#index', via: 'get'
  match '/menu', to: 'static_pages#menu', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'

  resources :order, only: [:index, :new, :create] 
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :organizations, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :destroy]
    resources :week_menu
  end

  namespace :api do
    resources :orders, only: [:index]
  end

  

end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-inverse navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Lunch Ordering', admin_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Users', admin_users_path %></li>
        <li><%= link_to 'Categories', admin_categories_path %></li>
        <li><%= link_to 'Items', admin_items_path %></li>
        <li><%= link_to 'Organizations', admin_organizations_path %></li>
        <li><%= link_to 'Menu for week', admin_week_menu_index_path %></li>
        <li><%= link_to 'Orders', admin_orders_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Go to user interface', root_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Lunch Ordering | Dashboard</title>
	<%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/admin/header' %>
	<%= render 'layouts/flash_messages' %>
	

	<div class="admin-container">
		<%= yield %>
	</div>

</div>
</body>
</html>