config/routes.rb
Rails.application.routes.draw do

  get 'order/information'

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "edit", to: "devise/registrations#edit"
  end

  root 'static_pages#home'
  match '/admin', to: 'admin#index', via: 'get'
  match '/menu', to: 'static_pages#menu', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'

  resources :order, only: [:index, :new, :create] 
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :organizations, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :destroy]
    resources :week_menu
  end

  namespace :api do
    resources :orders, only: [:index]
  end

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users

  validates :name, presence: true
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  def index
    @organization = Organization.order(created_at: :asc)
  end

  def new
    @organization = Organization.new
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to admin_organizations_path
      flash[:success] = 'Organization was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @organization = Organization.find(params[:id])

    if @organization.update(organization_params)
      redirect_to admin_organizations_path
      flash[:success] = 'Organization was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    redirect_to admin_organizations_path
    flash[:success] = 'Organization was successfully destroyed.'
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/admin/organizations/_form.html.erb
<%= f.label 'Name' %>
<%= f.text_field :name, class: "form-control" %>
<%= link_to 'Back', admin_organizations_path, class: "btn btn-default" %>
<%= f.submit 'Save', class: "btn btn-success" %><br>

app/views/admin/organizations/edit.html.erb
<div class="page-header">
	<h1>Edit Organization</h1>
</div>
<% if @organization.errors.any? %>
<div class="alert alert-danger">
	<h2>This form contains <%= pluralize(@organization.errors.count, "error") %>.</h2>
	
	<ul>
		<% @organization.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="admin-category-form">
	<%= form_for :organization, url: admin_organization_path(@organization), method: :patch do |f| %>
	<%= render 'form', :f => f %>
	<% end %>
</div>

app/views/admin/organizations/index.html.erb
<div class="page-header">
	<h1>Organizations <%= link_to 'Add Organization', new_admin_organization_path, class: "btn btn-success page-header-button" %></h1>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Id</th>
				<th>Organization</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @organization.each do |n| %>
			<tr>
				<td><%= n.id %></td>
				<td><%= n.name %></td>
				<td class="col-md-1">
					<%= link_to edit_admin_organization_path(n) do %>
					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
					<% end %>
					<%= link_to admin_organization_path(n), method: :delete,
					data: { confirm: 'Are you sure?' } do %>
					<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/organizations/new.html.erb
<div class="page-header">
	<h1>Add Organization</h1>
</div>
<% if @organization.errors.any? %>
<div class="alert alert-danger">
  <h2>This form contains <%= pluralize(@organization.errors.count, "error") %>.</h2>
  
  <ul>
    <% @organization.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="admin-category-form">
	<%= form_for :organization, :url => admin_organizations_path do |f| %>
  <%= render 'form', :f => f %>
  <% end %>
</div>