config/routes.rb
Rails.application.routes.draw do

  get 'order/information'

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "edit", to: "devise/registrations#edit"
  end

  root 'static_pages#home'
  match '/admin', to: 'admin#index', via: 'get'
  match '/menu', to: 'static_pages#menu', via: 'get'
  match '/profile', to: 'static_pages#profile', via: 'get'

  resources :order, only: [:index, :new, :create] 
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :organizations, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :destroy]
    resources :week_menu
  end

  namespace :api do
    resources :orders, only: [:index]
  end

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  validate :validate_items

  before_create :total_price

  belongs_to :user
  delegate :username, :to => :user, :prefix => true

  has_many :order_items
  has_many :items, through: :order_items, dependent: :destroy

  def total_price
    self.total = items.map(&:price).sum
  end

  def validate_items
    unless items.map(&:category_id).uniq.length == items.map(&:category_id).length && items.size == 3
      errors.add :items, 'Please select one item from each category'
    end
  end

  def self.getOrders
    date = Date.today
    @orders = Order.where(created_at: date..date.end_of_day)
    @orders.to_json
  end

  def self.find_orders(date_params)
    if date_params
      date = date_params.to_date
    else
      date = Date.today
    end
    Order.where(created_at: date..date.end_of_day).order(id: :desc) if date.present?
  end

  def self.date_orders(date_params)
    if date_params
      date = date_params.to_date
    else
      date = Date.today
    end
  end

  def self.total_orders(orders)
    orders.map(&:total).sum if orders.present?
  end
end

app/controllers/admin/week_menu_controller.rb
class Admin::WeekMenuController < AdminController
  def index
    @weekdays = WeekDay.all
  end

  def show
    @weekdays = WeekDay.find(params[:id])
    @weekdays.items.joins(:category)
  end

  def new
    @weekdays = WeekDay.new
  end

  def edit
    @weekdays = WeekDay.find(params[:id])
  end

  def create
    @weekdays = WeekDay.new(weekday_params)

    if @weekdays.save
      redirect_to admin_week_menu_index_path
      flash[:success] = 'Day menu was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @weekdays = WeekDay.find(params[:id])

    if @weekdays.update(weekday_params)
      redirect_to admin_week_menu_index_path
      flash[:success] = 'Day menu was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @weekdays = WeekDay.find(params[:id])
    @weekdays.destroy
    redirect_to admin_week_menu_index_path
    flash[:success] = 'Day menu was successfully destroyed.'
  end

  private

  def weekday_params
    params.fetch(:weekdays, {}).permit(:name).tap do |whitelisted|
      whitelisted[:item_ids] = params[:items][:item_ids] unless params[:items].nil?
    end
  end
end

app/views/admin/week_menu/_form.html.erb
<div class="day_menu_list">
	
	<label>Day</label>

	<div class="weekdays_button">
		<ul>
            <%= hidden_field_tag "weekdays[name]", nil %>
			<% ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"].each do |item| %>
			<li>
				<%= f.radio_button :name, item %> 
				<%= label_tag "weekdays_name_" + item.downcase, item %>
			</li>
			<% end %>

		</ul>
	</div>
	<%= hidden_field_tag "items[item_ids][]", nil %>
	<% Category.all.each do |category| %> 

	<label><%= category.name %></label>
	<ul>
		<% Item.where(category: category).each do |item| %>
		<li>
			<%= check_box_tag "items[item_ids][]", item.id, @weekdays.item_ids.include?(item.id), id: dom_id(item) %>
			<%= label_tag dom_id(item), item.name %>
		</li>
		<% end %>
	</ul>
	<% end %>
	
	<%= link_to 'Back', admin_week_menu_index_path, class: "btn btn-default" %>
	<%= f.submit 'Save', class: "btn btn-success" %><br>

app/views/admin/week_menu/edit.html.erb
<div class="page-header">
	<h1>Edit day menu</h1>
</div>
<% if @weekdays.errors.any? %>
<div class="alert alert-danger">
	<h2>This form contains <%= pluralize(@weekdays.errors.count, "error") %>.</h2>

	<ul>
		<% @weekdays.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="admin-category-form">
	
	<%= form_for :weekdays, url: admin_week_menu_path(@weekdays), method: :patch do |f| %>
	<%= render 'form', :f => f %>
	<% end %>
</div>

app/views/admin/week_menu/index.html.erb
<div class="page-header">
	<h1>Menu for week <%= link_to 'Add day menu', new_admin_week_menu_path, class: "btn btn-success page-header-button" %></h1>
</div>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Items</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @weekdays.each do |n| %>
			<tr>
				<td><%= n.name %></td>
				<td>count: <%= n.items.count %></td>
				<td class="col-md-1">
					<%= link_to admin_week_menu_path(n), class: "show_link" do %>
					<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
					<% end %>
					<%= link_to edit_admin_week_menu_path(n) do %>
					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
					<% end %>
					<%= link_to admin_week_menu_path(n), class: "destroy_link", method: :delete,
					data: { confirm: 'Are you sure?' } do %>
					<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/week_menu/new.html.erb
<div class="page-header">
	<h1>Day menu new</h1>
</div>
<% if @weekdays.errors.any? %>
<div class="alert alert-danger">
	<h2>This form contains <%= pluralize(@weekdays.errors.count, "error") %>.</h2>

	<ul>
		<% @weekdays.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="admin-category-form">
	<%= form_for :weekdays, :url => admin_week_menu_index_path do |f| %>
	<%= render 'form', :f => f %>
	<% end %>
</div>

app/views/admin/week_menu/show.html.erb
<div class="page-header">
	<h1>Day menu show</h1>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Week day</h3>
	</div>
	<div class="panel-body">
		
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Id</th>
						<th>Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @weekdays.id %></td>
						<td><%= @weekdays.name %></td>
					</tr>
				</tbody>
			</table>
		</div>

	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Items</h3>
	</div>
	<div class="panel-body">
		
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Category</th>
						<th>Name</th>
						<th>Price</th>
						
					</tr>
				</thead>
				<tbody>
					
					<% @weekdays.items.each do |n| %>
					<tr>
						<td><%= n.category.name %></td>
						<td><%= n.name %></td>
						<td><%= n.price %></td>
						
						
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

	</div>
</div>